name: Build Signed Release APK

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clean project
        run: |
          ./gradlew clean
          rm -rf app/build/

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Setup signing keys
        env:
          KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          KEYSTORE_PASS: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          echo "$KEYSTORE_BASE64" | base64 -d > keystore.jks
          echo "storeFile=keystore.jks" > keystore.properties
          echo "storePassword=$KEYSTORE_PASS" >> keystore.properties
          echo "keyAlias=$KEY_ALIAS" >> keystore.properties
          echo "keyPassword=$KEY_PASSWORD" >> keystore.properties
          mkdir -p app/
          mv keystore.* app/

      - name: Build signed APK
        run: ./gradlew assembleRelease --warning-mode=all

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Lawnicons-Signed
          path: app/build/outputs/apk/release/*.apk
