name: Build Signed APK

on:
  workflow_dispatch:
  push:
    tags: ['v*']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 步骤 1: 检出代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 步骤 2: 强制清理项目
      - name: Clean project
        run: |
          ./gradlew clean
          rm -rf app/build/

      # 步骤 3: 设置 JDK
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 21

      # 步骤 4: 配置签名密钥
      - name: Setup signing keys
        env:
          KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          echo "$KEYSTORE_BASE64" | base64 -d > keystore.jks
          echo "storeFile=keystore.jks" > keystore.properties
          echo "storePassword=$KEYSTORE_PASSWORD" >> keystore.properties
          echo "keyAlias=$KEY_ALIAS" >> keystore.properties
          echo "keyPassword=$KEY_PASSWORD" >> keystore.properties
          mv keystore.* app/

      # 步骤 5: 构建并显示弃用警告
      - name: Build APK with warnings
        run: ./gradlew assembleRelease --warning-mode=all

      # 步骤 6: 上传 APK
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Lawnicons-Signed-APK
          path: app/build/outputs/apk/release/*.apk
